name: CI Build Kernel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print greeting
        run: |
          echo "Workflow syntax is valid"
         
      - name: Load env file into GITHUB_ENV (safe)
        run: |
          set -eu
          ENV_FILE=".github/workflows/envs/kernel.env"
          if [ ! -f "$ENV_FILE" ]; then
            echo "Env file not found: $ENV_FILE"
            exit 1
          fi
          while IFS= read -r line || [ -n "$line" ]; do
            case "$line" in
              ''|\#*) continue ;;
            esac
            name="${line%%=*}"
            value="${line#*=}"
            expanded="$(eval "echo \"$value\"")"
            echo "${name}=${expanded}" >> "$GITHUB_ENV"
          done < "$ENV_FILE"
          echo "KERNEL_DIR=${GITHUB_WORKSPACE}" >> "$GITHUB_ENV"
          echo "OUT_DIR=${GITHUB_WORKSPACE}/${OUT_DIR}" >> "$GITHUB_ENV"
          echo "ANYKERNEL_DIR=${GITHUB_WORKSPACE}/${ANYKERNEL_DIR:-AnyKernel3}" >> "$GITHUB_ENV"
          TS=$(date +%Y%m%d_%H%M%S)
          echo "LOG_FILE=${GITHUB_WORKSPACE}/${LOG_PREFIX}_${TS}.txt" >> "$GITHUB_ENV"