name: CI - Validate env loader and simple build steps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-and-prepare:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load env file into GITHUB_ENV
        run: |
          set -eu
          ENV_FILE=".github/workflows/envs/kernel.env"
          if [ ! -f "$ENV_FILE" ]; then
            echo "Env file not found: $ENV_FILE"
            exit 1
          fi
          while IFS= read -r line || [ -n "$line" ]; do
            case "$line" in
              ''|\#*) continue ;;
            esac
            name="${line%%=*}"
            value="${line#*=}"
            # expand local references safely
            expanded="$(eval "echo \"$value\"")"
            echo "${name}=${expanded}" >> "$GITHUB_ENV"
          done < "$ENV_FILE"
          # runtime-derived values
          echo "KERNEL_DIR=${GITHUB_WORKSPACE}" >> "$GITHUB_ENV"
          echo "OUT_DIR=${GITHUB_WORKSPACE}/${OUT_DIR}" >> "$GITHUB_ENV"
          echo "ANYKERNEL_DIR=${GITHUB_WORKSPACE}/${ANYKERNEL_DIR}" >> "$GITHUB_ENV"
          TS=$(date +%Y%m%d_%H%M%S)
          echo "LOG_FILE=${GITHUB_WORKSPACE}/${LOG_PREFIX}_${TS}.txt" >> "$GITHUB_ENV"

      - name: Show loaded env (sanity)
        run: |
          set -eu
          echo "DEVICE=$DEVICE"
          echo "DEFCONFIG=$DEFCONFIG"
          echo "KERNEL_DIR=$KERNEL_DIR"
          echo "OUT_DIR=$OUT_DIR"
          echo "ANYKERNEL_DIR=$ANYKERNEL_DIR"
          echo "JOBS=$JOBS"
          echo "ARCH=$ARCH"
          echo "VERBOSE=$VERBOSE"
          echo "LOG_FILE=$LOG_FILE"

      - name: Prepare directories
        run: |
          set -eu
          mkdir -p "$OUT_DIR" "$OUT_DIR/modules_install" "$OUT_DIR/artifacts"
          ls -ld "$OUT_DIR" || true

      - name: Minimal build step (no kernel compile) to confirm workflow parses
        run: |
          set -eu
          echo "Skipping actual kernel build in this validation workflow"
          echo "Would run: make O=\"$OUT_DIR\" ARCH=$ARCH $DEFCONFIG"